WIP

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,9 +1,11 @@
 #!/bin/bash
-#set -e # halt script on error
+set -e # halt script on error
 #
-#bundle exec jekyll build
-
-wget https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-amd64.tar.gz
-tar -xzf ipfs-update_v1.5.2_linux-amd64.tar.gz
-ipfs-update/install.sh
-
+bundle exec jekyll build
+# get ipfs (version must match what you have on your node
+wget -qO- https://dist.ipfs.io/go-ipfs/v0.4.15/go-ipfs_v0.4.15_linux-amd64.tar.gz | tar xz
+# add jekyll output to ipfs
+ssh -N -L 5001:localhost:5001 ubuntu@34.229.86.216 &
+PATH=./go-ipfs/:$PATH
+HASH=`ipfs add -r -Q _site`
+echo $HASH
